# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envii < Formula
  desc "Encrypted .env & secrets manager with a TUI"
  homepage "https://github.com/Trickster-ID/envii"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.3/envii_0.1.3_darwin_amd64.tar.gz"
      sha256 "9d4b8522f919b6b92d3b4a5126dbf152707165d778fb7d622fd6a8380cf6de28"

      define_method(:install) do
        bin.install "envii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.3/envii_0.1.3_darwin_arm64.tar.gz"
      sha256 "18cd5548c7bbb7a40a28312d32c0fbeaa9693cc8980ee0bc244c1765d8f43e63"

      define_method(:install) do
        bin.install "envii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.3/envii_0.1.3_linux_amd64.tar.gz"
      sha256 "9d6391944ed89c37552c5af9779cbf7d881877bd36b7620d13ad803c9e9b5ba1"
      define_method(:install) do
        bin.install "envii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.3/envii_0.1.3_linux_arm64.tar.gz"
      sha256 "55b238d7e15e22c5f44ec3189fedefda4eb3c4ba6a74723024de58cb0ced9517"
      define_method(:install) do
        bin.install "envii"
      end
    end
  end
end
