# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envii < Formula
  desc "Encrypted .env & secrets manager with a TUI"
  homepage "https://github.com/Trickster-ID/envii"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.2/envii_0.1.2_darwin_amd64.tar.gz"
      sha256 "1e98fef9787f23b18fd96aa5492555bd61f0e78f9815fba7716b92899862c7ce"

      define_method(:install) do
        bin.install "envii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.2/envii_0.1.2_darwin_arm64.tar.gz"
      sha256 "8a72eec4e4b7a743f49ec690252b827e2a20716e76ac1b63e8ef0baa49fb21ee"

      define_method(:install) do
        bin.install "envii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.2/envii_0.1.2_linux_amd64.tar.gz"
      sha256 "d0b6a68dac5b4fb0924be21dd143e6306a89fbdf2bad64a0e901eff42c6e640b"
      define_method(:install) do
        bin.install "envii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Trickster-ID/envii/releases/download/v0.1.2/envii_0.1.2_linux_arm64.tar.gz"
      sha256 "70262299aebdf3d9d6df56cb6e9113e4cea606ba7b7e5858ad19253cfc4b58b8"
      define_method(:install) do
        bin.install "envii"
      end
    end
  end
end
