# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envii < Formula
  desc "Encrypted .env & secrets manager with a TUI"
  homepage "https://github.com/trickylab/envii"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/trickylab/envii/releases/download/v0.3.0/envii_0.3.0_darwin_amd64.tar.gz"
      sha256 "972d89b7073062b57fb8611ee5d92799420f1f428fab27b63502f80ed6f793dc"

      define_method(:install) do
        bin.install "envii"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/trickylab/envii/releases/download/v0.3.0/envii_0.3.0_darwin_arm64.tar.gz"
      sha256 "0a0473a690f708f2ff2836e554b72378cd9e1cce6e6950aff983868eaa8ecb0e"

      define_method(:install) do
        bin.install "envii"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/trickylab/envii/releases/download/v0.3.0/envii_0.3.0_linux_amd64.tar.gz"
      sha256 "06924afd9dce2a8b00e5ba2b875b593e3c508ce86b079bcfd9c8496dbcd8168f"
      define_method(:install) do
        bin.install "envii"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/trickylab/envii/releases/download/v0.3.0/envii_0.3.0_linux_arm64.tar.gz"
      sha256 "d6ac29bcd7cd477e74ac97571adf20a27969e865fcbecc2c7c11bc88ceb2c1b3"
      define_method(:install) do
        bin.install "envii"
      end
    end
  end
end
